# Generated by Django 3.2.5 on 2021-07-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=30)),
                ('course_language', models.CharField(max_length=30)),
                ('course_descreption', models.TextField()),
                ('course_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('courses', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='managment.course')),
            ],
        ),
    ]
