# Generated by Django 3.2.5 on 2021-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_alter_trainers_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
