# Generated by Django 3.2.5 on 2021-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_trainers_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='courses',
        ),
        migrations.AddField(
            model_name='trainers',
            name='courses',
            field=models.ManyToManyField(blank=True, to='managment.Course'),
        ),
    ]
