# Generated by Django 3.2.5 on 2021-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_auto_20210711_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='managment.Course'),
        ),
    ]
