# Generated by Django 3.2.5 on 2021-07-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_alter_trainers_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='courses',
            field=models.ManyToManyField(null=True, to='managment.Course'),
        ),
    ]
